openapi: 3.0.0
info:
  title: Inventory Management System API
  version: 1.0.0
  description: API documentation for the IMS backend
servers:
  - url: http://localhost:8080
paths:
  /register:
    post:
      tags: [Auth]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '409':
          description: User already exists

  /login:
    post:
      tags: [Auth]
      summary: Login and get auth cookie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '400':
          description: Invalid credentials

  /products:
    get:
      tags: [Products]
      summary: Get all products (paginated)
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Product list returned

    post:
      tags: [Products]
      summary: Add a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created

  /products/{id}/quantity:
    put:
      tags: [Products]
      summary: Update product quantity
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [quantity]
              properties:
                quantity:
                  type: integer
      responses:
        '200':
          description: Quantity updated

components:
  schemas:
    Product:
      type: object
      required:
        - name
        - type
        - sku
        - image_url
        - description
        - quantity
        - price
      properties:
        name:
          type: string
        type:
          type: string
        sku:
          type: string
        image_url:
          type: string
        description:
          type: string
        quantity:
          type: integer
        price:
          type: number
